#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# License: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: 4.1. immortalwrt+mtk原厂驱动

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  schedule:
    - cron: 0 3 * * 1
  push:
    branches: [ main ]

env:
  REPO_AUTHOR: immortalwrt
  REPO_NAME: combine
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-21.02
  DEVICE_SHORT_NAME: ax6000
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: ax6000/ax6000.config
  DIY_P1_SH: ax6000/diy-part1.sh
  DIY_P2_SH: ax6000/diy-part2.sh
  DIY_P3_SH: ax6000/diy-part3.sh
  SSH_ACTIONS: false
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
  NEED_CLEANUP: false
  NEED_CLONE: true


jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - name: 定义代码根路径
      run: |
        echo "SOURCE_ROOT=${{env.REPO_AUTHOR}}_${{env.REPO_NAME}}" >> $GITHUB_ENV
##########################################################################
    - name: 清理编译残存
      env:
        DEBIAN_FRONTEND: noninteractive
      if: env.NEED_CLEANUP == 'true'
      run: |
          sudo chown $USER:$GROUPS /workdir
          cd /workdir/${{env.SOURCE_ROOT}}
          rm -rf hanwckfop/
          rm -rf package/mtk/mtk
          rm -rf package/network/utils/fullconenat/fullconenat
          git checkout feeds.conf.default || true
          git checkout include/image.mk || true
          rm -rf dl/go-mod-cache/
          rm -rf /workdir/dl/go-mod-cache/
          rm -rf files
          rm -rf .config
          rm -rf  bin/targets/mediatek/mt7986/*.bin
          rm -rf package/v2ray-geodata
          rm -rf package/luci-app-ddns-go
          rm -rf package/lucky
          rm -rf package/cloudflared
          rm -rf package/mosdns
          rm -rf package/luci-app-mosdns
          rm -rf package/mycustom/openwrt-mos/mosdns
          rm -rf package/luci-app-alist
          rm -rf package/openwrt-adguardhome/
          rm -rf package/z_*
          git checkout package || true
##########################################################################

    - name: 定义代码根路径
      run: |
        echo "SOURCE_ROOT=${{env.REPO_AUTHOR}}_${{env.REPO_NAME}}" >> $GITHUB_ENV

    - name: 设定时区
      uses: zcong1993/setup-timezone@master
      with:
        timezone: "Asia/Shanghai"

    - name: 检出项目分支
      uses: actions/checkout@main
      with:
        ref: hanwckf

    - name: 安装编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL https://tinyurl.com/depends-ubuntu-2004) || true
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: 自定义go路径
      run: |
        [ ! -e /workdir/go ]  && wget -qO- https://go.dev/dl/go1.19.4.linux-amd64.tar.gz | tar -zxC /workdir/ || true


    - name: 克隆源代码
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone --depth 2 $REPO_URL -b  $REPO_BRANCH $SOURCE_ROOT || true
        ln -sf /workdir/$SOURCE_ROOT $GITHUB_WORKSPACE/openwrt
        cd /workdir/$SOURCE_ROOT
        COMMIT2ID=`git log -2 --pretty=format:"%H" |sed -n '2p'`
        sed -i 's/REBOOT=.*/REBOOT='"${COMMIT2ID}"'/g' scripts/getver.sh
        cd ..

    - name: 克隆第三方代码
      run: |
        cd openwrt

        mkdir dl || true
        git clone --depth 1 https://github.com/hanwckf/immortalwrt-mt798x.git hanwckfop || true
        mv hanwckfop/dl/* dl || true
        mv hanwckfop/package/boot/uboot-envtools/files/mediatek package/boot/uboot-envtools/files/mediatek
        rm -rf package/network/services/hostapd
        mv hanwckfop/package/network/services/hostapd package/network/services/hostapd
        rm -rf package/network/utils/iw
        mv hanwckfop/package/network/utils/iw package/network/utils/iw
        rm -rf package/network/utils/iwinfo
        mv hanwckfop/package/network/utils/iwinfo package/network/utils/iwinfo
        rm -rf package/network/utils/wireless-tools
        mv hanwckfop/package/network/utils/wireless-tools package/network/utils/wireless-tools
        mv hanwckfop/package/mtk package/mtk

        rm -rf target/linux/generic
        mv hanwckfop/target/linux/generic target/linux/generic
        rm -rf target/linux/generic/backport-5.4/702-Revert-net-dsa-b53-Fix-valid-setting-for-MDB-entries.patch
        rm -rf target/linux/generic/backport-5.4/703-v5.5-0001-net-dsa-b53-Add-support-for-MDB.patch
        rm -rf target/linux/generic/backport-5.4/707-v5.7-0016-net-dsa-b53-Fix-valid-setting-for-MDB-entries.patch

        rm -rf target/linux/mediatek
        mv hanwckfop/target/linux/mediatek target/linux/mediatek
        #new iw version compile need update libnl-tiny
        mv hanwckfop/package/libs/libnl-tiny/Makefile package/libs/libnl-tiny/Makefile

        wget https://github.com/immortalwrt/immortalwrt/raw/openwrt-21.02/package/firmware/wireless-regdb/patches/600-custom-change-txpower-and-dfs.patch -q --no-check-certificate -O package/firmware/wireless-regdb/patches/600-custom-change-txpower-and-dfs.patch

        rm -rf package/network/config/firewall
        mv hanwckfop/package/network/config/firewall package/network/config/firewall
        mv hanwckfop/package/network/utils/fullconenat package/network/utils/fullconenat
        mkdir -p package/network/utils/iptables/patches
        mv hanwckfop/package/network/utils/iptables/patches/900-bcm-fullconenat.patch package/network/utils/iptables/patches/900-bcm-fullconenat.patch
        sed -i "s/add_list system.ntp.server='0.*/add_list system.ntp.server='ntp1.aliyun.com'"/ package/base-files/files/bin/config_generate
        sed -i "s/add_list system.ntp.server='1.*/add_list system.ntp.server='time1.cloud.tencent.com'"/ package/base-files/files/bin/config_generate
        sed -i "s/add_list system.ntp.server='2.*/add_list system.ntp.server='time.ustc.edu.cn'"/ package/base-files/files/bin/config_generate
        sed -i "s/add_list system.ntp.server='3.*/add_list system.ntp.server='ntp2.aliyun.com'"/ package/base-files/files/bin/config_generate
        sed -i "s/set system\.\@system\[-1\].timezone='UTC'/set system\.\@system\[-1\]\.timezone='CST-8'\n\t\tset system\.\@system\[-1\]\.zonename='Asia\/Shanghai'/" package/base-files/files/bin/config_generate
        mkdir -p package/mycustom
        #xray 科学用，luci-app-xray防火墙规则没开关，可能会导致无线中继功能异常
        git clone --depth 1 -b master https://github.com/yichya/luci-app-xray package/mycustom/luci-app-xray || true
        sed -i 's/create tp_spec_dst_bp hash:net hashsize 64.*$/create tp_spec_dst_bp hash:net hashsize 64 maxelem 1000000/g' package/mycustom/luci-app-xray/root/usr/share/xray/gen_ipset_rules.lua
        sed -i 's/flush_dnsmasq$//g' package/mycustom/luci-app-xray/root/etc/init.d/xray
        sed -i 's/setup_dnsmasq$//g' package/mycustom/luci-app-xray/root/etc/init.d/xray
        sed -i '/service dnsmasq restart/d' package/mycustom/luci-app-xray/root/etc/hotplug.d/iface/01-transparent-proxy-ipset.fw3
        git clone --depth 1 https://github.com/Mitsuhaxy/luci-i18n-xray-zh-cn.git package/mycustom/luci-i18n-xray-zh-cn || true
        #sed -i '/include $(INCLUDE_DIR)\/package.mk/d' package/mycustom/luci-i18n-xray-zh-cn/Makefile
        #fix make menuconfig error
        sed -i '/DEPENDS/d' package/mycustom/luci-i18n-xray-zh-cn/Makefile
        #v2ray 反向连接回家里用
        #git clone --depth 1 -b luci2 https://github.com/BI7PRK/luci-app-v2ray.git package/mycustom/luci-app-v2ray || true
        git clone --depth=1 https://github.com/fw876/helloworld.git package/mycustom/helloworld || true
        git clone --depth=1 -b v4_EOL https://github.com/QiuSimons/openwrt-mos.git package/mycustom/openwrt-mos || true
        #sed -i 's@geoip.dat@geoip.dat\n\twget -O- "https://github.com/misakaio/chnroutes2/raw/master/chnroutes.txt" | grep -v "#" > $(1)/etc/mosdns/geoip_cn.txt@g' package/mycustom/openwrt-mos/v2ray-geodata/Makefile
        #sed -i 's@geoip_cn.txt.$(GEOIP_VER)@geoip_cn.txt.$(GEOIP_VER)\nwget -O- "https://github.com/misakaio/chnroutes2/raw/master/chnroutes.txt" | grep -v "#" > $(1)/etc/mosdns/geoip_cn.txt@g' package/mycustom/openwrt-mos/v2ray-geodata/Makefile || true
        git clone --depth=1 https://github.com/muziling/openwrt-package.git package/mycustom/muzipkg || true
        mkdir -p package/mycustom/muzipkg/my-files/files
        wget -O- "https://github.com/misakaio/chnroutes2/raw/master/chnroutes.txt" | grep -v "#" > package/mycustom/muzipkg/my-files/files/geoip_cn.txt
        git clone --depth=1 https://github.com/jerrykuku/luci-theme-argon.git package/mycustom/luci-theme-argon || true
        git clone --depth 1 -b master https://github.com/garypang13/luci-theme-edge package/mycustom/luci-theme-edge || true
        git clone --depth=1 https://github.com/kuoruan/openwrt-upx.git package/mycustom/openwrt-upx || true
        #for shadowsocks, impletement encrypt algorithm
        mv hanwckfop/package/libs/openssl/Config.in package/libs/openssl/Config.in
        rm -rf package/libs/mbedtls
        mv hanwckfop/package/libs/mbedtls package/libs/mbedtls
        rm -rf package/libs/ustream-ssl
        mv hanwckfop/package/libs/ustream-ssl package/libs/ustream-ssl
        rm -rf package/libs/wolfssl
        mv hanwckfop/package/libs/wolfssl package/libs/wolfssl
        #update version
        rm -rf package/libs/libmnl
        mv hanwckfop/package/libs/libmnl package/libs/libmnl
        rm -rf package/libs/libnfnetlink
        mv hanwckfop/package/libs/libnfnetlink package/libs/libnfnetlink
        ./scripts/feeds update -a
        wget https://raw.githubusercontent.com/coolsnowwolf/lede/master/package/lean/ddns-scripts_aliyun/update_aliyun_com.sh -q --no-check-certificate -O feeds/packages/net/ddns-scripts/files/usr/lib/ddns/update_aliyun_com.sh
        chmod +x feeds/packages/net/ddns-scripts/files/usr/lib/ddns/update_aliyun_com.sh
        echo -e '{\n\t"name": "aliyun.com",\n\t"ipv4": {\n\t\t"url": "update_aliyun_com.sh"\n\t}\n}'  >feeds/packages/net/ddns-scripts/files/usr/share/ddns/default/aliyun.com.json
        sed -i 's|$(INSTALL_BIN) ./files/usr/lib/ddns/dynamic_dns_updater.sh|$(INSTALL_BIN) ./files/usr/lib/ddns/dynamic_dns_updater.sh $(1)/usr/lib/ddns\n\t$(INSTALL_BIN) ./files/usr/lib/ddns/update_aliyun_com.sh|' feeds/packages/net/ddns-scripts/Makefile
        #sed -i "/tristate /a\\\t   default \$(shell if [ '\$(lang)' == 'zh_Hans' ]\; then echo y\; else echo n\; fi)" feeds/luci/luci.mk
        sed -i "s/option lang .*/option lang 'zh_cn' /" feeds/luci/modules/luci-base/root/etc/config/luci
        sed -i 's|mediaurlbase.*$|mediaurlbase /luci-static/argon|g' feeds/luci/modules/luci-base/root/etc/config/luci
        ./scripts/feeds install -a
        #grep -v '^#' hanwckfop/defconfig/mt7981-ax3000.config > .config
        cp hanwckfop/defconfig/mt7986-ax6000.config .config
        echo CONFIG_LUCI_LANG_zh_Hans=y >> .config
        #echo CONFIG_PACKAGE_luci-i18n-xray-zh-cn=y >> .config
        wget https://raw.githubusercontent.com/muziling/openwrt-autocompile/master/360t7/Makefile -O target/linux/mediatek/Makefile
        rm -rf package/base-files/files/sbin/wifi
    - name: 自定义软件源(DIY_P1)
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        chmod +x $DIY_P1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: 自定义源代码(DIY_P2)
      run: |
        [ -e files ] && mv files openwrt/files
        chmod a+x openwrt/files/etc/init.d/disable-ipv6.sh
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH

    - name: SSH链接管理
      uses: P3TERX/ssh2actions@v1.0.0
      if: false

    - name: 下载插件
      run: cd openwrt && ./scripts/feeds update -a

    - name: 读取插件
      run: cd openwrt && ./scripts/feeds install -a

    - name: 生成编译配置
      run: |
        cd openwrt
        cat defconfig/mt7986-ax6000.config >> .config || true
        cd $GITHUB_WORKSPACE
        [ -e $CONFIG_FILE ] && cat $CONFIG_FILE >> $GITHUB_WORKSPACE/openwrt/.config
        cd openwrt
        cat .config
        make defconfig

    - name: 下载软件包
      id: package
      run: |
        [ ! -e openwrt/dl/ ] && mkdir openwrt/dl
        [ -e dl ] && cp -rf dl/* openwrt/dl/
        [ -e /workdir/dl ] && cp -rf /workdir/dl/* openwrt/dl/
        cd openwrt
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
      if: true

    - name: 针对特定软件的自定义设置(DIY_P3)
      run: |
        chmod +x $DIY_P3_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P3_SH

    - name: 开始编译固件
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) ||make -j2 || make -j1 V=s
        echo "{compile_status}={success}" >> $GITHUB_OUTPUT
        echo "FILE_TIME=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        echo "FILE_DATE=$(date +"%Y%m%d")" >> $GITHUB_ENV

    - name: 查看磁盘使用情况
      if: (!cancelled())
      run: df -hT

    - name: 查看目录
      if: |
      run: ls -al openwrt/bin/targets/*/* || true

    - name: 上传bin压缩目录
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt_bin${{ env.DEVICE_SHORT_NAME }}${{ env.FILE_DATE }}
        path: openwrt/bin/packages/aarch64_cortex-a53

    - name: 整理编译好的固件
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages && mkdir packages
        find -name "*esxi-flat.vmdk*" | xargs -i mv -f {} packages
        find -name "*kernel.bin*" | xargs -i mv -f {} packages
        find -name "*rootfs*" | xargs -i mv -f {} packages
        find -name "*.manifest*" | xargs -i mv -f {} packages
        find -name "*vmlinuz*" | xargs -i mv -f {} packages
        find -name "*esxi.vmdk*" | xargs -i mv -f {} packages
        rm -rf packages
        (for var in *.bin; do mv "$var" "${var%.bin}-$(cat version.buildinfo | cut -d '-' -f2).bin"; done) ||true
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "{status}={success}" >> $GITHUB_OUTPUT

    - name: 上传固件到github action
      uses: actions/upload-artifact@main
      if: ${{env.STATE.compile_status}} == 'success' && !cancelled()
      with:
        name: ${{env.REPO_AUTHOR}}-${{env.REPO_NAME}}-${{env.REPO_BRANCH}}-${{ env.DEVICE_SHORT_NAME }}-${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE}}

    - name: 创建release标签
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_ENV
        echo "{tag.status}={success}" >> $GITHUB_OUTPUT

    - name: 发布至release
      uses: softprops/action-gh-release@v1
      if: ${{env.STATE.tag_status}} == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        name: 「${{env.FILE_DATE}}」-「${{env.REPO_AUTHOR}}-${{env.REPO_NAME}}-${{env.REPO_BRANCH}}-${{env.DEVICE_SHORT_NAME}}」
        tag_name: ${{env.release_tag}}
        body_path: release-combined.md
        files: |
          ${{ env.FIRMWARE }}/*

    - name: 查看目录
      if: |
      run: ls -al openwrt/bin/targets/*/* || true

    - name: 删除旧的Releases
      uses: JAM2199562/delete-older-releases@v0.2.0
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 99
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

    - name: 清理 workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 99
        keep_minimum_runs: 99
