#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# License: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: 4.1. immortalwrt+mtk原厂驱动

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  schedule:
    - cron: 0 3 */7 * *
  # push:
  #   branches: [ main ]

env:
  REPO_AUTHOR: immortalwrt
  REPO_NAME: immortalwrt
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-21.02
  SOURCE_ROOT: immortalwrt.21.02-combine
  DEVICE_SHORT_NAME: x86
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: immortalwrt/x86/immortalwrt-x86.config
  DIY_P1_SH: immortalwrt/x86/diy-immortalwrt-part1.sh
  DIY_P2_SH: immortalwrt/x86/diy-immortalwrt-part2.sh
  DIY_P3_SH: immortalwrt/x86/diy-immortalwrt-part3.sh
  SSH_ACTIONS: false
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
  NEED_CLEANUP: false
  NEED_CLONE: true

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: hanwckf
        fetch-depth: 0

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
        sudo -E apt-get update
        sudo -E apt-get -qq install $(curl -fsSL https://tinyurl.com/depends-ubuntu-2004) || true
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        rm -rf /workdir/$SOURCE_ROOT
        df -hT $PWD
        git clone --depth 2 $REPO_URL -b  $REPO_BRANCH $SOURCE_ROOT || true
        ln -sf /workdir/$SOURCE_ROOT $GITHUB_WORKSPACE/openwrt
        cd /workdir/$SOURCE_ROOT
        COMMIT2ID=`git log -2 --pretty=format:"%H" |sed -n '2p'`
        sed -i 's/REBOOT=.*/REBOOT='"${COMMIT2ID}"'/g' scripts/getver.sh
        cd ..

    - name: Clone 3rd code
      run: |
        cd openwrt

        mkdir dl || true
        git clone --depth 1 https://github.com/hanwckf/immortalwrt-mt798x.git hanwckfop

        mv hanwckfop/dl/* dl
        # 下面这句先不执行，因为我还并没有patch
        # find . -maxdepth 1 -type f -iname '*.patch' -print0|xargs -n1 -0 patch -p 1 -i

        mv hanwckfop/package/boot/uboot-envtools/files/mediatek package/boot/uboot-envtools/files/mediatek

        rm -rf package/network/services/hostapd
        mv hanwckfop/package/network/services/hostapd package/network/services/hostapd
        rm -rf package/network/utils/iw
        mv hanwckfop/package/network/utils/iw package/network/utils/iw
        rm -rf package/network/utils/iwinfo
        mv hanwckfop/package/network/utils/iwinfo package/network/utils/iwinfo
        rm -rf package/network/utils/wireless-tools
        mv hanwckfop/package/network/utils/wireless-tools package/network/utils/wireless-tools

        mv hanwckfop/package/mtk package/mtk

        rm -rf target/linux/generic
        mv hanwckfop/target/linux/generic target/linux/generic
        rm -rf target/linux/generic/backport-5.4/702-Revert-net-dsa-b53-Fix-valid-setting-for-MDB-entries.patch
        rm -rf target/linux/mediatek
        mv hanwckfop/target/linux/mediatek target/linux/mediatek
        #new iw version compile need update libnl-tiny
        mv hanwckfop/package/libs/libnl-tiny/Makefile package/libs/libnl-tiny/Makefile

        wget https://github.com/immortalwrt/immortalwrt/raw/openwrt-21.02/package/firmware/wireless-regdb/patches/600-custom-change-txpower-and-dfs.patch -q --no-check-certificate -O package/firmware/wireless-regdb/patches/600-custom-change-txpower-and-dfs.patch

        rm -rf package/network/config/firewall
        mv hanwckfop/package/network/config/firewall package/network/config/firewall
        mv hanwckfop/package/network/utils/fullconenat package/network/utils/fullconenat
        mkdir -p package/network/utils/iptables/patches
        mv hanwckfop/package/network/utils/iptables/patches/900-bcm-fullconenat.patch package/network/utils/iptables/patches/900-bcm-fullconenat.patch


        git clone --depth=1 https://github.com/jerrykuku/luci-theme-argon.git package/mycustom/luci-theme-argon
        git clone --depth 1 -b master https://github.com/garypang13/luci-theme-edge package/mycustom/luci-theme-edge
        git clone --depth=1 https://github.com/kuoruan/openwrt-upx.git package/mycustom/openwrt-upx

